start_vm.py: Fix target name handling
This patch fix bb_output search (issue with wrong arch name being
selected for qemu) which caused qemu-system-riscv64 to be used for all
the targets:

>ERROR: [Errno 2] No such file or directory: u'qemu-system-riscv64' (1.05 s)

Signed-off-by: Roman Pletnev <rpletnev@ilbers.de>
Signed-off-by: Anton Mikanovich <amikan@ilbers.de>